#! /bin/sh
#
# C H K
#
# Last modified on Sat Oct 12 19:56:59 2019 
#
#
SYS_TYPE=`uname -s`
#
# Linux and other similar systems need sudo,
#  however Mac OSX does not need sudo
if [ "$SYS_TYPE" = "Darwin" ]
then
 PROG_UNDER_TEST=../checktime.py
elif [ "$SYS_TYPE" = "Linux" ]
then
 PROG_UNDER_TEST="sudo ../checktime.py"
else
 SYS_UNAME_O=`uname -o`
 if [ "$SYS_UNAME_O" = "Cygwin" ]
 then
  PROG_UNDER_TEST=../checktime.py
 else
  PROG_UNDER_TEST="sudo ../checktime.py"
 fi
fi
#
#
echo
echo ----------- House keeping tests: Version Number ----------------
####
## Show version number
$PROG_UNDER_TEST $1 --verbose --no-ping --no-time-stamp localhost
##
echo
echo ----------- House keeping tests: Basic Debug Info ----------------
####
## Show Most Basic Debug Info
$PROG_UNDER_TEST $1 -v --debug -P -T localhost
##
echo
echo ----------- Successful --Ping and Timestamp work-------
####
## Low (6-7mS) RTT ISP time source
$PROG_UNDER_TEST $1 tic.ntp.telstra.net 
##
## Med (18-19mS) RTT ISP time source
$PROG_UNDER_TEST $1 time.optus.net
##
## 42-43mS RTT NZ time source
$PROG_UNDER_TEST $1 s2.ntp.net.nz
##
## 226-227mS RTT US time source
$PROG_UNDER_TEST $1 clock.he.net
##
## 309-312mS RTT French time source
$PROG_UNDER_TEST $1 ntp.obspm.fr
##
#
echo
echo ---------- Successful --Big Endian timestamps returned--------
####
## FreeBSD and Ubuntu machines
$PROG_UNDER_TEST $1 www.freebsd.org www.ubuntu.org
##
## Seems like a python program should naturally team up with www.python.org
$PROG_UNDER_TEST $1 www.python.org
#
#
echo
echo ---------- Successful --Little Endian timestamps returned--------
####
## Ping and timestamp succeed, but timestamp is non-standard (little endian)
$PROG_UNDER_TEST $1 wwh-2.onthe.net.au
#
#
echo
echo ---------- Mostly successful --Non-Standard timestamp indication--
####
## Ping and timestamp succeed, but timestamp has non-standard flag set
$PROG_UNDER_TEST $1 58.96.102.9
#
#
echo
echo ---------- Mostly unsuccessful --Destination Unreachable------
####
## Ping succeeds but timestamp gets a destination unreachable reply
$PROG_UNDER_TEST $1 time.iinet.com.au
##
## Both Ping and timestamp get a destination unreachable reply
$PROG_UNDER_TEST $1 www.openbsd.org
#
#
echo
echo ---------- Unsuccessful --Ping fails, but Timestamp works--
####
## Ping fails, but timestamp succeeds
$PROG_UNDER_TEST $1 ntp-m.obspm.fr
#
#
echo
echo ---------- Unsuccessful --Ping works, but no Timestamp--
####
## Ping succeeds, but timestamp fails
$PROG_UNDER_TEST $1 ntp.tpg.com.au
#
#
echo
echo ---------- Unsuccessful on purpose --Both Ping and Timestamp fail, but DNS ok--
####
## DNS ok, but no replies
$PROG_UNDER_TEST $1 time.windows.com
#
#
echo
echo ---------- Unsuccessful on purpose --Test response to non-existant name--
####
## DNS fails
$PROG_UNDER_TEST $1 time.microsoft.com
#

