#! /bin/sh
#
# C H K
#
# Last modified on Sun Dec  3 17:26:21 2017 
#
#
SYS_TYPE=`uname -s`
#
# Linux and other similar systems need sudo,
#  however Mac OSX does not need sudo
if [ "$SYS_TYPE" = "Darwin" ]
then
 PROG_UNDER_TEST=../checktime.py
elif [ "$SYS_TYPE" = "Linux" ]
then
 PROG_UNDER_TEST="sudo ../checktime.py"
else
 SYS_UNAME_O=`uname -o`
 if [ "$SYS_UNAME_O" = "Cygwin" ]
 then
  PROG_UNDER_TEST=../checktime.py
 else
  PROG_UNDER_TEST="sudo ../checktime.py"
 fi
fi
#
echo
echo ----------- Successful --Ping and Timestamp work--
##
## Local ADSL Router
$PROG_UNDER_TEST $1 10.0.0.138
####
#### Local Windows XP SP3 computer, after ensuring echo+timestamp is on with; -
####  netsh firewall set icmpsetting 13 enable
####  netsh firewall set icmpsetting 8 enable
# $PROG_UNDER_TEST $1 -r 10.0.0.84
####
#### Local Windows 10 Home computer, after ensuring timestamp is on with; -
####  netsh advfirewall firewall add rule name="Allow-ICMP-V4-Timestamp" protocol=icmpv4:13,0 dir=in action=allow
# $PROG_UNDER_TEST $1 -r 10.0.0.62
####
#### Local Android Phone
# $PROG_UNDER_TEST $1 android-ae6a6ccb5592abd3
##
## ISP time sources
$PROG_UNDER_TEST $1 tic.ntp.telstra.net toc.ntp.telstra.net
####
#### Other ISP time sources
# $PROG_UNDER_TEST $1 time.optus.net clock.exetel.com.au ntp.internode.on.net ntp.iprimus.com.au
####
#### Australian National Measurements Institute (Australian Time Standard)
# $PROG_UNDER_TEST $1 ntp.sydney.nmi.gov.au ntp.melbourne.nmi.gov.au ntp.adelaide.nmi.gov.au ntp.brisbane.nmi.gov.au
####
#### Swedish time sources
# $PROG_UNDER_TEST $1 ntp1.sp.se time1.stupi.se
####
#### Three DNS names, but one IP Address
# $PROG_UNDER_TEST $1 time.apple.asia.com time.microsoft.asia.com time.linux.asia.com
####
#### Hosted in the cloud (by akamai?, akamaiedge?)
# $PROG_UNDER_TEST $1 www.vodafone.com.au www.optus.com.au www.abc.net.au www.commbank.com.au
##
## FreeBSD and NetBSD machines
$PROG_UNDER_TEST $1 www.freebsd.com www.netbsd.org
##
## Seems like a python program should naturally team up with www.python.org
$PROG_UNDER_TEST $1 www.python.org
#
#
echo
echo ---------- Unsuccessful so far --Destination Unreachable--
##
## Ping succeeds but timestamp gets a destination unreachable reply
$PROG_UNDER_TEST $1 time.iinet.com.au
##
## Both Ping and timestamp get a destination unreachable reply
$PROG_UNDER_TEST $1 www.openbsd.org
#
#
echo
echo ---------- Unsuccessful so far --Ping works, but no Timestamp--
####
#### Local Windows XP SP3 computer, after ensuring timestamp is off with; -
####  netsh firewall set icmpsetting 13 disable
#### and ensure Ping (echo) is on with; -
####  netsh firewall set icmpsetting 8 enable
# $PROG_UNDER_TEST $1 -r 10.0.0.84
####
#### Local Windows 10 Home computer, after ensuring previously created firewall
#### rule allowing timestamp is removed with; -
####  netsh advfirewall firewall delete rule name="Allow-ICMP-V4-Timestamp" protocol=icmpv4:13,0 dir=in
# $PROG_UNDER_TEST $1 -r 10.0.0.62
####
#### Local Apple iPad tablet
# $PROG_UNDER_TEST $1 iPad
####
# $PROG_UNDER_TEST $1 time.google.com
##
$PROG_UNDER_TEST $1 ntp.tpg.com.au www.telstra.com.au
####
# $PROG_UNDER_TEST $1 ntp.aussiebroadband.com.au
##
$PROG_UNDER_TEST $1 time.asia.apple.com
####
# $PROG_UNDER_TEST $1 time.apple.com time.apple.com.au
####
# $PROG_UNDER_TEST $1 ntp.adam.com.au
#
#
echo
echo ---------- Unsuccessful so far --Ping fails and no Timestamp, but DNS ok--
##
$PROG_UNDER_TEST $1 time.windows.com
##
$PROG_UNDER_TEST $1 ntp.perth.nmi.gov.au
####
#### Local Windows XP SP3 computer, after ensuring echo+timestamp is off with; -
####  netsh firewall set icmpsetting 13 disable
####  netsh firewall set icmpsetting 8 disable
# $PROG_UNDER_TEST $1 -r 10.0.0.84
#
#
echo
echo ---------- Unsuccessful on purpose --Test response to non-existant name--
$PROG_UNDER_TEST $1 time.microsoft.com
#

